---
# yamllint disable rule:line-length
name: PR

on: # yamllint disable-line rule:truthy rule:comments
  pull_request:
    branches:
      - master

concurrency:
  group: pr-checks-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      XDG_CACHE_HOME: /tmp/.cache
      XDG_DATA_HOME: /tmp/.local/share
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: "false"
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
